name: ACTION

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force'
        required: true
        type: choice
        options: [yes, no]

jobs:
  Notify:
    name: Notify
    runs-on: ubuntu-latest

    environment: Devel

    steps:
      - name: View github context
        run: echo "${{ toJson(github) }}"

      - name: Show info about built Docker image
        uses: andyone/pachca-action@master
        with:
          webhook: ${{secrets.PACHCA_WEBHOOK}}
          payload-format: raw
