name: ACTION

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force'
        required: true
        type: choice
        options: [yes, no]

jobs:
  Context:
    name: Context
    runs-on: ubuntu-latest

    steps:
      - name: View github context
        run: |
          JSON_DATA=$(cat << EOF
          {
            "repository": "${{github.repository}}",
            "run_attempt": ${{github.run_attempt}},
            "run_number": ${{github.run_number}},
          }
          EOF
          )

          echo "$JSON_DATA" > payload.json

          cat payload.json
